version: '3.6'
services:
  websocket:
    container_name: "ddev-${DDEV_SITENAME}-websocket"
    image: ddev-websocket
    build:
      context: ../
      dockerfile: .ddev/websocket/Dockerfile
    volumes:
      - ./:/app:cached
    ports:
      - "8888:8888"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
      com.docker.compose.project: ddev-$DDEV_SITENAME
